version: '3.8'

services:
  audit:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./auditReports:/app/auditReports
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
    mem_limit: 8g
