[profile.default]
src = "contracts"
out = "foundry-out"
libs = ["node_modules", "lib"]
test = "tests"
cache_path = "foundry-cache"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
verbosity = 3

# 添加remappings以解决导入问题
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=node_modules/@openzeppelin/"
]

[fuzz]
runs = 1000

[invariant]
runs = 100
depth = 10